//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documentTypes()
        {
            this.documents = new HashSet<documents>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool onBoard { get; set; }
        public int orgID { get; set; }
        public int vehicleTypeID { get; set; }
        public Nullable<int> alarm1 { get; set; }
        public Nullable<int> alarm2 { get; set; }
        public bool download { get; set; }
        public string createUser { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string updateUser { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<documents> documents { get; set; }
        public virtual organizationLists organizationLists { get; set; }
        public virtual vehicleTypeLists vehicleTypeLists { get; set; }
    }
}
