//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Documents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public documents()
        {
            this.files = new HashSet<files>();
        }
    
        public int id { get; set; }
        public int docTypeID { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> dateS { get; set; }
        public Nullable<System.DateTime> datePo { get; set; }
        public int carID { get; set; }
        public string createUser { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string updateUser { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public bool onBoard { get; set; }
    
        public virtual documentTypes documentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<files> files { get; set; }
        public virtual cars cars { get; set; }
    }
}
